language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_install:
    - npm i
script:
  - npm run test
#after_success:
#  - 'cat ./coverage/lcov.info && ./node_modules/.bin/coveralls'
